### ISSUE TITLE
Q: Are there plans to support Golang?

### ISSUE THREAD

**Issue by kwk** [fabric8-analytics/fabric8-analytics-vscode-extension#45]
Hi,

this is a great extension! Are there plans to support Golang?

Currently there's no de-facto package manager for Go but we ([fabric8-wit](https://github.com/fabric8-services/fabric8-wit)) have made good experience with a tool called [glide](https://glide.sh/).

IIRC in Go 1.10 there will be an integrated package manager.

To give you an idea of how a packaging file looks like in glide, this is ours: https://github.com/fabric8-services/fabric8-wit/blob/master/glide.yaml

```yaml
package: github.com/fabric8-services/fabric8-wit
homepage: https://github.com/fabric8-services/fabric8-wit
license: Apache-2.0
import:
- package: github.com/fabric8-services/fabric8-tenant
  subpackages:
  - design
- package: github.com/fabric8-services/fabric8-notification
  subpackages:
  - design
- package: github.com/fabric8-services/fabric8-auth
  version: da575b14ac9ceb113f18f1c1cab75be256460d64
  subpackages:
  - design
- package: github.com/dgrijalva/jwt-go
  version: ^3.0.0
- package: github.com/goadesign/goa
  version: ^1.3.0
  vcs: git
  subpackages:
  - client
  - cors
  - design
  - design/apidsl
  - goagen
  - goagen/codegen
  - goagen/gen_app
  - goagen/gen_controller
  - goagen/utils
  - goatest
  - middleware
  - middleware/security/jwt
- package: github.com/armon/go-metrics
  version: 9a4b6e10bed6220a1665955aa2b75afc91eb10b3
- package: gopkg.in/square/go-jose.v2
  version: ^2.1.2
- package: github.com/dimfeld/httptreemux
  version: ^3.1.0
- package: github.com/lsegal/gucumber
- package: github.com/spf13/cobra
- package: golang.org/x/net
  subpackages:
  - context
- package: github.com/jteeuwen/go-bindata
  version: ^3.0.7
  subpackages:
  - '...'
- package: github.com/elazarl/go-bindata-assetfs
  subpackages:
  - go-bindata-assetfs
- package: golang.org/x/tools
  subpackages:
  - go/ast/astutil
- package: gopkg.in/yaml.v2
- package: github.com/kr/pretty
- package: github.com/kr/text
- package: github.com/pilu/fresh
- package: github.com/howeyc/fsnotify
- package: github.com/mattn/go-colorable
- package: github.com/pilu/config
- package: github.com/jinzhu/gorm
  version: 9c9de896864248929269a7cb2d64ed73b5fdf834
- package: github.com/mattn/go-isatty
  version: ^0.0.1
- package: github.com/axw/gocov
  subpackages:
  - gocov
- package: github.com/wadey/gocovmerge
- package: gopkg.in/asaskevich/govalidator.v4
- package: github.com/lib/pq
- package: github.com/stretchr/testify
  version: ^1.1.4
  subpackages:
  - assert
  - suite
- package: github.com/robfig/cron
  version: ^1.0.0
- package: github.com/andygrunwald/go-jira
- package: github.com/google/go-github
  subpackages:
  - github
- package: github.com/google/go-querystring
  subpackages:
  - query
- package: github.com/spf13/viper
- package: github.com/fsnotify/fsnotify
  version: ^1.3.1
- package: github.com/hashicorp/hcl
- package: github.com/magiconair/properties
  version: ^1.7.0
- package: github.com/mitchellh/mapstructure
- package: github.com/pelletier/go-toml
  version: ^0.5.0
- package: github.com/pkg/errors
  version: ^0.8.0
- package: github.com/spf13/afero
- package: github.com/spf13/cast
- package: github.com/spf13/jwalterweatherman
- package: golang.org/x/oauth2
- package: github.com/dnaeon/go-vcr
  version: 9d71b8a6df86e00127f96bc8dabc09856ab8afdb
  subpackages:
  - recorder
- package: github.com/russross/blackfriday
- package: github.com/microcosm-cc/bluemonday
- package: github.com/shurcooL/sanitized_anchor_name
- package: github.com/golang/lint
  subpackages:
  - golint
- package: github.com/fzipp/gocyclo
- package: github.com/sirupsen/logrus
- package: github.com/sourcegraph/syntaxhighlight
- package: github.com/jstemmer/go-junit-report
- package: github.com/sourcegraph/annotate
- package: github.com/sergi/go-diff
  subpackages:
  - diffmatchpatch
- package: github.com/xeipuuv/gojsonschema
- package: github.com/xeipuuv/gojsonreference
- package: github.com/xeipuuv/gojsonpointer
- package: github.com/prometheus/client_golang
```

In order to have reproducible builds, there's also a lock file to contain exact (hash) version information. This is our lock file: https://github.com/fabric8-services/fabric8-wit/blob/master/glide.lock

```yaml
hash: caa9d898279820017887be76710f5ceccd0a6ba8d7fc4ccc3bbd40578fdfa4c4
updated: 2017-11-08T03:37:24.617276964+01:00
imports:
- name: github.com/andygrunwald/go-jira
  version: 9d1f282f93af41553ddb53b0116a8cdb75b4837a
- name: github.com/armon/go-metrics
  version: 9a4b6e10bed6220a1665955aa2b75afc91eb10b3
- name: github.com/asaskevich/govalidator
  version: 7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877
- name: github.com/axw/gocov
  version: c77561ca0c0cb1ed5d4ce4a912a75f5532566422
  subpackages:
  - gocov
- name: github.com/beorn7/perks
  version: 3ac7bf7a47d159a033b107610db8a1b6575507a4
  subpackages:
  - quantile
- name: github.com/davecgh/go-spew
  version: 6d212800a42e8ab5c146b8ace3490ee17e5225f9
  subpackages:
  - spew
- name: github.com/dgrijalva/jwt-go
  version: dbeaa9332f19a944acb5736b4456cfcc02140e29
- name: github.com/dimfeld/httppath
  version: c8e499c3ef3c3e272ed8bdcc1ccf39f73c88debc
- name: github.com/dimfeld/httptreemux
  version: 13dde8a00d96b369e7398490fd8a3af9ca114b84
- name: github.com/dnaeon/go-vcr
  version: 9d71b8a6df86e00127f96bc8dabc09856ab8afdb
  subpackages:
  - cassette
  - recorder
- name: github.com/elazarl/go-bindata-assetfs
  version: 9a6736ed45b44bf3835afeebb3034b57ed329f3e
  subpackages:
  - go-bindata-assetfs
- name: github.com/fabric8-services/fabric8-auth
  version: da575b14ac9ceb113f18f1c1cab75be256460d64
  subpackages:
  - configuration
  - design
  - errors
  - log
  - login/tokencontext
  - rest
  - token
- name: github.com/fabric8-services/fabric8-notification
  version: a3c7adb29a8ec1e0aab2af4f9a2d3c852d0daaef
  subpackages:
  - design
- name: github.com/fabric8-services/fabric8-tenant
  version: 5ce38dea6287d9bac7789a8bc24556867a4fcee6
  subpackages:
  - design
- name: github.com/fatih/structs
  version: dc3312cb1a4513a366c4c9e622ad55c32df12ed3
- name: github.com/fsnotify/fsnotify
  version: 629574ca2a5df945712d3079857300b5e4da0236
- name: github.com/fzipp/gocyclo
  version: 6acd4345c835499920e8426c7e4e8d7a34f1bb83
- name: github.com/goadesign/goa
  version: 5646a430cdeb66983d5ace3384e0a667c185abc7
  vcs: git
  subpackages:
  - client
  - cors
  - design
  - design/apidsl
  - dslengine
  - goagen
  - goagen/codegen
  - goagen/gen_app
  - goagen/gen_controller
  - goagen/utils
  - goatest
  - logging/logrus
  - middleware
  - middleware/gzip
  - middleware/security/jwt
  - uuid
  - version
- name: github.com/golang/lint
  version: c7bacac2b21ca01afa1dee0acf64df3ce047c28f
  subpackages:
  - golint
- name: github.com/golang/protobuf
  version: 8ee79997227bf9b34611aee7946ae64735e6fd93
  subpackages:
  - proto
- name: github.com/google/go-github
  version: 5c45bca952b96dedace6c307caff915483013003
  subpackages:
  - github
- name: github.com/google/go-querystring
  version: 9235644dd9e52eeae6fa48efd539fdc351a0af53
  subpackages:
  - query
- name: github.com/hashicorp/go-immutable-radix
  version: 8aac2701530899b64bdea735a1de8da899815220
- name: github.com/hashicorp/golang-lru
  version: 0a025b7e63adc15a622f29b0b2c4c3848243bbf6
  subpackages:
  - simplelru
- name: github.com/hashicorp/hcl
  version: 37ab263305aaeb501a60eb16863e808d426e37f2
  subpackages:
  - hcl/ast
  - hcl/parser
  - hcl/scanner
  - hcl/strconv
  - hcl/token
  - json/parser
  - json/scanner
  - json/token
- name: github.com/howeyc/fsnotify
  version: f0c08ee9c60704c1879025f2ae0ff3e000082c13
- name: github.com/inconshreveable/mousetrap
  version: 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
- name: github.com/jinzhu/gorm
  version: 9c9de896864248929269a7cb2d64ed73b5fdf834
- name: github.com/jinzhu/inflection
  version: 74387dc39a75e970e7a3ae6a3386b5bd2e5c5cff
- name: github.com/jstemmer/go-junit-report
  version: 15422cf504f9dc030386499a5c68053a38763e58
- name: github.com/jteeuwen/go-bindata
  version: bbd0c6e271208dce66d8fda4bc536453cd27fc4a
  subpackages:
  - '...'
- name: github.com/kr/pretty
  version: cfb55aafdaf3ec08f0db22699ab822c50091b1c4
- name: github.com/kr/text
  version: 7cafcd837844e784b526369c9bce262804aebc60
- name: github.com/lib/pq
  version: 4a82388ebc5138c8289fe9bc602cb0b3e32cd617
  subpackages:
  - oid
- name: github.com/lsegal/gucumber
  version: 71608e2f6e76fd4da5b09a376aeec7a5c0b5edbc
- name: github.com/magiconair/properties
  version: be5ece7dd465ab0765a9682137865547526d1dfb
- name: github.com/manveru/faker
  version: 717f7cf83fb78669bfab612749c2e8ff63d5be11
- name: github.com/mattn/go-colorable
  version: d228849504861217f796da67fae4f6e347643f15
- name: github.com/mattn/go-isatty
  version: 0360b2af4f38e8d38c7fce2a9f4e702702d73a39
- name: github.com/matttproud/golang_protobuf_extensions
  version: fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a
  subpackages:
  - pbutil
- name: github.com/microcosm-cc/bluemonday
  version: e79763773ab6222ca1d5a7cbd9d62d83c1f77081
- name: github.com/mitchellh/mapstructure
  version: 5a0325d7fafaac12dda6e7fb8bd222ec1b69875e
- name: github.com/pelletier/go-buffruneio
  version: c37440a7cf42ac63b919c752ca73a85067e05992
- name: github.com/pelletier/go-toml
  version: 13d49d4606eb801b8f01ae542b4afc4c6ee3d84a
- name: github.com/pilu/config
  version: 3eb99e6c0b9a2dae0f56f05552c06ca5a643919b
- name: github.com/pilu/fresh
  version: 315385b584ff3845a255844aeb2b7d14a26648b0
- name: github.com/pkg/errors
  version: 645ef00459ed84a119197bfb8d8205042c6df63d
- name: github.com/pmezard/go-difflib
  version: d8ed2627bdf02c080bf22230dbb337003b7aba2d
  subpackages:
  - difflib
- name: github.com/prometheus/client_golang
  version: e51041b3fa41cece0dca035740ba6411905be473
  subpackages:
  - prometheus
- name: github.com/prometheus/client_model
  version: fa8ad6fec33561be4280a8f0514318c79d7f6cb6
  subpackages:
  - go
- name: github.com/prometheus/common
  version: a6ab08426bb262e2d190097751f5cfd1cfdfd17d
  subpackages:
  - expfmt
  - internal/bitbucket.org/ww/goautoneg
  - model
- name: github.com/prometheus/procfs
  version: 454a56f35412459b5e684fd5ec0f9211b94f002a
- name: github.com/robfig/cron
  version: b024fc5ea0e34bc3f83d9941c8d60b0622bfaca4
- name: github.com/russross/blackfriday
  version: 5f33e7b7878355cd2b7e6b8eefc48a5472c69f70
- name: github.com/satori/go.uuid
  version: b061729afc07e77a8aa4fad0a2fd840958f1942a
- name: github.com/sergi/go-diff
  version: feef008d51ad2b3778f85d387ccf91735543008d
  subpackages:
  - diffmatchpatch
- name: github.com/shurcooL/sanitized_anchor_name
  version: 1dba4b3954bc059efc3991ec364f9f9a35f597d2
- name: github.com/sirupsen/logrus
  version: c078b1e43f58d563c74cebe63c85789e76ddb627
- name: github.com/sourcegraph/annotate
  version: f4cad6c6324d3f584e1743d8b3e0e017a5f3a636
- name: github.com/sourcegraph/syntaxhighlight
  version: c95ac474b7cb9c711f4591b553a2caaa24ea3d37
- name: github.com/spf13/afero
  version: 2f30b2a92c0e5700bcfe4715891adb1f2a7a406d
  subpackages:
  - mem
- name: github.com/spf13/cast
  version: 24b6558033ffe202bf42f0f3b870dcc798dd2ba8
- name: github.com/spf13/cobra
  version: 9495bc009a56819bdb0ddbc1a373e29c140bc674
- name: github.com/spf13/jwalterweatherman
  version: 33c24e77fb80341fe7130ee7c594256ff08ccc46
- name: github.com/spf13/pflag
  version: 5ccb023bc27df288a957c5e994cd44fd19619465
- name: github.com/spf13/viper
  version: 651d9d916abc3c3d6a91a12549495caba5edffd2
- name: github.com/stretchr/testify
  version: 69483b4bd14f5845b5a1e55bca19e954e827f1d0
  subpackages:
  - assert
  - require
  - suite
- name: github.com/trivago/tgo
  version: 4a656addb20609ba4cb4d20219a2f6c27aeb142c
  subpackages:
  - tcontainer
- name: github.com/wadey/gocovmerge
  version: b5bfa59ec0adc420475f97f89b58045c721d761c
- name: github.com/xeipuuv/gojsonpointer
  version: 6fe8760cad3569743d51ddbb243b26f8456742dc
- name: github.com/xeipuuv/gojsonreference
  version: e02fc20de94c78484cd5ffb007f8af96be030a45
- name: github.com/xeipuuv/gojsonschema
  version: 3f523f4c14b6e925da10475eb0447c2f28614aac
- name: github.com/zach-klippenstein/goregen
  version: 795b5e3961ea1912fde60af417ad85e86acc0d6a
- name: golang.org/x/crypto
  version: 81e90905daefcd6fd217b62423c0908922eadb30
  subpackages:
  - ed25519
  - ed25519/internal/edwards25519
- name: golang.org/x/net
  version: b1a2d6e8c8b5fc8f601ead62536f02a8e1b6217d
  subpackages:
  - context
  - html
  - html/atom
  - websocket
- name: golang.org/x/oauth2
  version: da3ce8d62a7f77aadfda06cb82bd604d6469c645
  subpackages:
  - internal
- name: golang.org/x/sys
  version: 478fcf54317e52ab69f40bb4c7a1520288d7f7ea
  subpackages:
  - unix
- name: golang.org/x/text
  version: 47a200a05c8b3fd1b698571caecbb68beb2611ec
  subpackages:
  - transform
  - unicode/norm
- name: golang.org/x/tools
  version: a888bfdffa4526cc6987572bca9a2c6b7758290f
  subpackages:
  - go/ast/astutil
- name: google.golang.org/appengine
  version: ca59ef35f409df61fa4a5f8290ff289b37eccfb8
  subpackages:
  - internal
  - internal/base
  - internal/datastore
  - internal/log
  - internal/remote_api
  - internal/urlfetch
  - urlfetch
- name: gopkg.in/asaskevich/govalidator.v4
  version: 7664702784775e51966f0885f5cd27435916517b
- name: gopkg.in/square/go-jose.v2
  version: f8f38de21b4dcd69d0413faf231983f5fd6634b1
  subpackages:
  - cipher
  - json
- name: gopkg.in/yaml.v2
  version: a5b47d31c556af34a302ce5d659e6fea44d90de0
testImports: []
```
